# SPDX-FileCopyrightText: Copyright (c) 2020-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
AllCops:
  NewCops: disable
  Exclude:
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.3
  SuggestExtensions: false
Layout/LineLength:
  Max: 100
Layout/EndOfLine:
  EnforcedStyle: lf
Style/MultilineTernaryOperator:
  Enabled: false
Metrics/BlockLength:
  Max: 50
Layout/ParameterAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
